### ISSUE TITLE
Task list for kubecon CAPI lab

### ISSUE THREAD

**Issue by killianmuldoon** [ykakarap/kubecon-na-22-capi-lab#2]
# WIP

- [x] Presentation and video
   - [x] Create base slide deck @killianmuldoon  - [link](https://docs.google.com/presentation/d/1CRPhzMO5wvUy-Um47a_aPGnYxJviq1rM/edit#slide=id.p1)
   - [x] CAPI overview presentation @shivi28
   - [x] Ensure video format, upload etc. is correct
   - [x] Submit by October 14th @sbueringer
   - [x] Assign on-the-day presentation sections to individuals 
        - Prereqs, Quickstart Visualizer: Killian
        - Change topology + MHC: Jack
        - Upgrades + Lifecycle hooks: Yuvaraj
        - Self-hosted + deletion: Stefan
   - [x] Record video for presentation @shivi28
   - [x] Submit final slides before the actual tutorial to sched and repository

- [x] Verify Offline functionality - ensure there is a version that works without internet access @sbueringer @killianmuldoon
   - [x] Validate Windows flow (works until quickstart now, have to re-test the whole thing later)
      - [x]  MHC patch not working
      - [x] Self-hosted clusterctl init should use proper commands
   - [x] Validate Linux flow (works until quickstart now, have to re-test the whole thing later)
   - [x] Validate MacOS flow (works until quickstart now, have to re-test the whole thing later)
       - [x] Preload images for coredns wrong architecture 
       - [x] Preload images doesn't work for test-extension and visualiser. Requires multi-arch build. (@sbueringer/@ykakarap)

- [x] Backup presentation flow (anything that can go wrong)
   - [x] Ensure offline functionality on 3+ laptops
   - [x] Just quickly brainstorm some ideas, e.g.:
     - Development with Tilt 

# Done

 - [x] Troubleshooting guide #34 
    - [x] docker prune / docker system df
    - [x] fedora set ulimits @killianmuldoon
    - [x] systematic troubleshooting guide
      - describe cluster, look at individual resource with describe => ctrl logs => exec into machines + look at logs
    - [x] https://kind.sigs.k8s.io/docs/user/known-issues/

- [x] Finalize
   - [x] adding numbers to md / YAML files (@killianmuldoon) #29 
   - [x] adding cluster deletion/cleanup to the relevant sections (@killianmuldoon) #29 
   - [x] scaling Warnings (especially for Windows) (@killianmuldoon) @29
     - including drop scale up to 3 cp nodes in upgrade section
   - [x] Ensure the transitions between sections are correct (including links to the md's) (@killianmuldoon) #29
   - [x] Add CAPI links to bottom of MDs as a "find out more" section (@killianmuldoon) #35 
   - [x] Finalize top-level markdown @killianmuldoon/@sbueringer
   - [x] Update text of description @killianmuldoon/@sbueringer
   - [x] Include repo and slides in talk description @killianmuldoon/@sbueringer
   - [x] Add operations slides to the presentation @jackfrancis/@ykakarap

- [x] Prerequisites for tutorial @sbueringer #1 
   - [x] Validate Windows flow
   - [x] Validate Linux flow
   - [x] Validate MacOS flow (tested with amd64)
   
- [x] Cluster API with Docker Quickstart @killianmuldoon #5 
   - [x] Validate Windows flow
   - [x] Validate Linux flow
   - [x] Validate MacOS flow
   - [x] Add quick start slides to the presentation
   
- [x] Cluster API operations guide 
   - [x] Deploying the CAPI visualizer @sbueringer #7 
   - [x] Changing the Cluster Topology @jackfrancis #12 
   - [x] MachineHealthChecks and remediation @sbueringer  #21 
   - [x] Upgrade Kubernetes version @jackfrancis #24 
   - [x] Cluster lifecycle hooks (@ykakarap) #13 
   - [x] Self hosted management cluster @ykakarap #19
   - [x] Deleting a cluster && cleaning up CAPI @killianmuldoon #23 

- [x] Other
   - [x] Update to Cluster API v1.2.3 (@sbueringer) #4 
   - [x] Bump to Cluster API v1.2.4 once it's released (@sbueringer)
   - [x] Bump visualizer to image with optimized size (@sbueringer)
   - [x] Internal VMware blog post (@killianmuldoon)
   - [x] Update speaker list (include @ykakarap)

**Comment by ykakarap** [comment]
Kindest images in gcr:
* gcr.io/kakaraparthy-devel/kindest/haproxy:v20210715-a6da3463
* gcr.io/kakaraparthy-devel/kindest/node:v1.25.2
* gcr.io/kakaraparthy-devel/kindest/node:v1.24.6
* gcr.io/kakaraparthy-devel/docker.io/calico/cni:v3.24.1
* gcr.io/kakaraparthy-devel/docker.io/calico/kube-controllers:v3.24.1
* gcr.io/kakaraparthy-devel/docker.io/calico/node:v3.24.1
